- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Free Trial (2d4bdde6-47de-486e-95d3-ca6cd67b359a)'
    subscriptionId: '2d4bdde6-47de-486e-95d3-ca6cd67b359a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'storageRG'
    location: 'Australia East'
    templateLocation: 'Linked artifact'
    csmFile: 'vh'
    deploymentMode: 'Incremental'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more::
# https://aka.ms/yaml

trigger:
- master


pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
